version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.Api
    ports:
      - "5095:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=descuentor;Username=postgres;Password=postgres
    depends_on:
      - db

  webassembly:
    build:
      context: .
      dockerfile: Dockerfile.WebAssembly
    ports:
      - "80:80"
    depends_on:
      - api

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: descuentor
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: